version: "3"

services:
  auth:
    build: ./services/auth/.
    container_name: auth_app
    restart: always
    networks:
      - app
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./.env:/app/.env
      - ./common:/app/common
      - ./database:/app/database
    ports:
      - 1111:1111

  user:
    build: ./services/user/.
    container_name: user_auth_app
    restart: always
    networks:
      - app
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./.env:/app/.env
      - ./common:/app/common
      - ./database:/app/database
    ports:
      - 1112:1112

  msg_worker:
    build: ./workers/msg/.
    container_name: msg_worker
    restart: always
#    ports:
#      - 8082:8081
    depends_on:
      - rabbitmq
    volumes:
      - ./.env:/app/.env
      - ./common/:/app/common
      - ./database:/app/database
    networks:
      - app

  alembic:
    build: ./alembic/.
    restart: on-failure
    networks:
      - app
    volumes:
      - ./.env:/app/.env
      - ./common/:/app/common
      - ./database:/app/database
      - ./alembic/:/app/alembic
      - ./alembic.ini/:/app/alembic.ini
    command: alembic upgrade head

  db:
    image: postgres
    restart: always
    shm_size: 512mb
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    networks:
      - app
    ports:
      - 8881:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB_NAME}
      PGDATA: "/var/lib/postgresql/data/pgdata"

  adminer:
    image: adminer
    restart: always
    networks:
      - app
    ports:
      - 8988:8080

  redis:
    image: redis
    restart: always
    networks:
      - app
#    ports:
#      - '6379:6379'
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:4-management  # Используем образ с панелью управления (Management UI)
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"    # Порт для AMQP (обмен сообщениями)
      - "15672:15672"  # Порт для веб-интерфейса управления (Management UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest    # Имя пользователя по умолчанию
      RABBITMQ_DEFAULT_PASS: guest    # Пароль пользователя по умолчанию
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  pg-data:
  redis:
    driver: local